#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath:$PWD/concourse:$PWD/gopath/src/github.com/vito/houdini/Godeps_linux/_workspace
export PATH=$PWD/gopath/bin:$PWD/concourse/bin:$PATH

go get github.com/jteeuwen/go-bindata/go-bindata

./gopath/src/github.com/concourse/bin/scripts/build-linux

go-bindata -nomemcopy -pkg bindata -o gopath/src/github.com/concourse/bin/bindata/bindata.go linux/...

# must be build with 'daemon' flag because of docker packages :|
go build \
  -tags daemon \
  -o binary-linux/concourse_linux_amd64 \
  github.com/concourse/bin/cmd/concourse
